// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcrgxjukgzphamoejsuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcmd4anVrZ3pwaGFtb2Vqc3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDI4OTEsImV4cCI6MjA3MjQ3ODg5MX0.e7Io-Fw11CXcBw7OOM_Qe03CpS7c0XPq6Qslvdikxtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});